name: miniplex_nmea_reader
description: Un projet Dart pour se connecter au Miniplex 2Wi via Wi-Fi et récupérer les trames NMEA
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  multicast_dns: ^0.3.0  # Utiliser ce package pour mDNS
  path: ^1.8.0
  socket_io_client: ^2.0.0

dev_dependencies:
  test: ^1.16.6

flutter:
  assets:
    - assets/
